python main.py \
    --proxy_types PROXY_TYPES \
    --start START_ARCH_NUM \
    --end END_ARCH_NUM \
    --search_space nasbench201 \
    --data PATH_TO_DATA \
    --dataset DATASET \
    --save_dir PATH_TO_SAVE \
    --api_loc PATH_TO_NB201_API \
    --rob_api_loc PATH_TO_RobustNB201_API \
    --e2e